bihealth/cubi-tk

cubi_tk/isa_tpl/__init__.py
The configuration was pointing to `isatab-generic`, seems to me it should be `isatab-single_cell_rnaseq` instead.
=> Fix configuration for single_cell_rnaseq ISAtab template

.github/workflows/ci.yml, .gitignore, cubi_tk/snappy/itransfer_common.py
closes #35 
**Summary** 
Changed `itransfer` Landing Zone priority: now the automatic behaviour is to first looks 
for active Landing Zones before creating a new one.
**Tests**
1. There were no additional error nor warning messages while using the automatic `pytest`.
2. Passed manual tests in sandbox tests ([logs](https://github.com/bihealth/cubi-tk/files/6048485/35_cubi-tk_tests.log)).
=> Change in itransfer lz priority

cubi_tk/snappy/models.py, cubi_tk/snappy/varfish_upload.py, requirements/base.txt, tests/data/germline_sheet.tsv, tests/data/test_config.yaml, tests/test_snappy_models.py, tests/test_snappy_varfish_upload.py
closes #46 
**Changes**
* Added possibility to use custom pedigree definition field also during VarFish upload.
**Tests**
* Tested with internal cohort. After changes there is no attempt to upload sibling data to VarFish, only index.
=> Use pedigree field during VarFish upload

cubi_tk/snappy/pull_sheets.py, cubi_tk/sodar/pull_raw_data.py
- Extends `cubi_tk/snappy/pull_sheets.py` to support datasets without `Family`, `Father`, `Mother`, `Sex` and/or `Disease status` as comments in the sample sheet.
- `mRNA_seq` also added to supported library types.
- The library name is used as default for the folder name when missing.
Note that the call to `api.investigations.get` is replaced by `api.samplesheet.retrieve`. I hope that it is correct...
=> Enable generic & cancer dataset

cubi_tk/snappy/common.py, cubi_tk/snappy/itransfer_common.py, cubi_tk/snappy/varfish_upload.py, tests/conftest.py, tests/data/find_snappy/.snappy_pipeline/config.yaml, tests/data/find_snappy/.snappy_pipeline/sheet.tsv, tests/data/germline_sheet_multi_batch.tsv, tests/test_snappy_common.py, tests/test_snappy_itransfer_common.py, tests/test_snappy_itransfer_ngs_mapping.py, tests/test_snappy_itransfer_raw_data.py, tests/test_snappy_itransfer_variant_calling.py, tests/test_snappy_varfish_upload.py
closes #51 
**Changes**
All changes involve commands: `cubi-tk snappy itransfer-*`
* New flag `--last-batch`, last batch number to be transferred.
* Flag `start-batch` renamed for consistency , now `--first-batch`.
* Argument `biomedsheet_tsv` removed. Now getting sample sheet path based on config file, i.e., `.snappy_pipeline/config.yaml`.
* Removed possibility to accept iRODS path as destination. Now code only accepts landing zone or project UUIDs - path defined using API.
**Test**
Tested using internal cohort 'PID' (last available batch:14) without transferring variant calling files from the landing zone. Same result: 392 files (1.2 Gb).
Commands:
```
cubi-tk snappy itransfer-variant-calling --start-batch 13  .snappy_pipeline/<PID>.tsv  <PID_UUID>
cubi-tk snappy …
```
=> Improve itransfer subcommands

cubi_tk/sodar/download_sheet.py
closes #52 
**Changes**
* Update `sodar-cli` API call for `cubi-tk sodar download-sheet`
**Test**
* Tested with internal SODAR project ''seasnap test data'': `cubi-tk sodar download-sheet <PROJECT_UUID> isatab`
Output:
```
isatab/
|-- a_monocytes.txt
|-- i_Investigation.txt
`-- s_monocytes.txt
```
=> Update sodar-cli api call for sodar download-sheet

cubi_tk/snappy/__init__.py, cubi_tk/snappy/itransfer_common.py, cubi_tk/snappy/itransfer_step.py, tests/test_snappy_itransfer_step.py
**Aim:** Generic function to add the output of any `snappy` step to SODAR.
**Remarks:**
- In the somatic/cancer branch, many steps should be added to SODAR: `somatic_variant_calling`, `somatic_variant_annotation`, `somatic_targeted_seq_cnv_calling`, `somatic_wgs_cnv_calling`, perhaps `hla_typing`, `gene_expression_quantification`, `somatic_gene_fusion_calling`, and others that will be implemented "soon".
- Supersedes `itransfer-ngs-mapping` & `itransfer-variant-calling`.
- Implementation is not ideal: missing step names are not caught in `cubi_tk.snappy.itransfer_common.check_args`, but in `cubi_tk.snappy.itransfer_common.execute`. This is because `cubi_tk.sodar.ingest_fastq` creates a sub-class of `SnappyItransferCommandBase`, without defining `step_name` and without creating a …
=> Add generic itransfer-step

cubi_tk/snappy/pull_raw_data.py
Fixes [issue #78: cubi-tk snappy pull-raw-data fails because of missing option --allow-missing](https://github.com/bihealth/cubi-tk/issues/78)
=> Bug fix: add --allow-missing to snappy pull-raw-data

cubi_tk/irods/__init__.py, cubi_tk/irods/check.py, cubi_tk/sea_snap/check_irods.py, requirements/base.txt, setup.cfg
Here's my solution for re-implementing the iRODS check using python-irodsclient instead of shell hacks.
Some notes:
- For opening a session via the client we require the user's iRODS password. My solution was to prompt for this in CLI as storing passwords as clear text is a no-no. I'm open for better ideas.
- Based on my own testing (which includes running this on an iRODS collection with 2500*2 files) opening several sessions and running in parallel does not seem to speed up the checks much at all. We might want to ditch the parallel stuff altogether to simplify the code, but that's your call.
- The alternate version of irods check under sea-snap does not work with the initial commit. If you give thumbs up to this one I should be quite easily able to refactor the hard coded parts to work …
=> Reimplement irods check using python client (#59)

cubi_tk/isa_tpl/isatab-tumor_normal_triplets/{{cookiecutter.i_dir_name}}/a_{{cookiecutter.assay_prefix}}_transcriptome_profiling_nucleotide_sequencing.txt, cubi_tk/isa_tpl/isatab-tumor_normal_triplets/{{cookiecutter.i_dir_name}}/a_{{cookiecutter.assay_prefix}}_{{cookiecutter.assay_name}}.txt, cubi_tk/isa_tpl/isatab-tumor_normal_triplets/{{cookiecutter.i_dir_name}}/s_{{cookiecutter.s_file_name}}.txt
Microarray was fixed, but this one still fails.
=> Fix trailing spaces in tumor_normal_triplets template (#100)

cubi_tk/snappy/check_remote.py, tests/test_snappy_check_remote.py
closes #103 
**Changes**
* Restructured code to deal with multiple versions of the same file in SODAR. 
* Added warning if multiple versions are present. 
* Now only displaying one type of report - decreased verbose.
=> Hotfix: snappy check-remote to deal with multiple versions of files in SODAR

cubi_tk/snappy/__init__.py, cubi_tk/snappy/parse_sample_sheet.py, cubi_tk/snappy/pull_all_data.py, cubi_tk/snappy/pull_data_common.py, cubi_tk/snappy/pull_processed_data.py, cubi_tk/snappy/pull_raw_data.py, tests/test_snappy_parse_sample_sheet.py, tests/test_snappy_pull_processed_data.py, tests/test_snappy_pull_raw_data.py
closes #29 , closes #113 
**Changes**
* Restrict `snappy pull-raw-data` to FASTQ files. Default behavior: looks for FASTQ file names that contain the sample identifier. Otherwise, it looks for path in SODAR that contain the library names (_e.g._, 'P001-N1-DNA1-WGS1').
* Repurposed old `pull-raw-data` as `pull-all-data`. As the name suggests it will download all data associated with a sample from SODAR.
=> Restrict `snappy pull-raw-data` to FASTQ files

cubi_tk/sodar/add_ped.py
=> `sodar add-ped`: fixed input type for argument 'input_ped_file' (#127)

cubi_tk/snappy/common.py, cubi_tk/snappy/varfish_upload.py, requirements/base.txt
closes #129, closes #132 
**Changes**
* Included `*_export_external` workflows in `varfish_upload` default.
* Added new argument `--external-data`, if present it won't filter files based on common `snappy` tool combination.
* Included `*_export_external` workflows in kickoff common dependencies .
Note: only merge after https://github.com/bihealth/snappy-pipeline/pull/216 is complete.
=> Adjust to `snappy` export external data workflows (#129, #132)

cubi_tk/snappy/pull_data_common.py
This fixes #175 by first comparing the filepath and only issuing the irods get if the file does not already exists.
This does not perform a md5 checksum
Irods pythonclient directly issues a download from the get command if a localpath is included:   [ def get(self, path, local_path = None, num_threads = DEFAULT_NUMBER_OF_THREADS, **options):](https://github.com/irods/python-irodsclient/blob/bb03bb5bccf650838ae6468e6f90c60325a07997/irods/manager/data_object_manager.py#L111)
This unfortunately does not perform a md5 check against an existing file and instead only offers clobbering or fails with an exception.
We can also handle this in the exception handler and trust the irods library to raise the correct expection. This would be more dependent on the specific irods library logic.
=> feat: allow for existing files when using irods download

cubi_tk/irods/check.py, cubi_tk/snappy/check_remote.py, cubi_tk/snappy/pull_data_common.py, cubi_tk/snappy/pull_processed_data.py, cubi_tk/snappy/pull_raw_data.py, cubi_tk/snappy/retrieve_irods_collection.py, cubi_tk/sodar/check_remote.py, tests/helpers.py, tests/test_snappy_check_remote.py, tests/test_snappy_pull_data_common.py, tests/test_snappy_pull_processed_data.py, tests/test_snappy_pull_raw_data.py, tests/test_sodar_check_remote.py
Still work in progress but already reduces irods pull commands to <30s. Querying all files from a single sodar assay takes ~2.5s. The slow part is reading each `md5` checksum.
Since irods already offers native checksumming, its unclear whether the current md5 checksums are really necessary. This should be cleared up.
=> feat: Fast irods querying

.github/workflows/main.yml
Issue reported in #137 seems to be fixed. This reverts changes in #138 to fix #139.
=> fix: Unpin Mamba version in CI workflow

cubi_tk/common.py
Added missing parameter `recursive=True` as described here: https://docs.python.org/3/library/glob.html
=> fix: actually match files recursively

requirements/base.txt
v0.1 of cubi-isa-templates contained a workaround for NCIT accession IDs which is no longer needed and in fact clashes with the fix deployed in the latest SODAR version.
Also, Cookiecutter fixed a display bug: https://github.com/cookiecutter/cookiecutter/issues/1939
=> fix: Update ISA-tpl dependencies

cubi_tk/snappy/itransfer_common.py, cubi_tk/sodar/ingest_fastq.py, docs_manual/man_ingest_fastq.rst, tests/conftest.py, tests/test_sodar_ingest_fastq.py
This was initially only intended to solve #198 , but I ended up adding some additional changes / enhancements to other aspects of `cubi-tk sodar ingest-fastq` and other (`cubi-tk snappy itransfer` functions).
Added Features:
- Added the `--match-column` flag that enables comparing the contents of the  "(?<sample>?)" match group from the src-regex against any specified column of the assay table of a given project (automatically determined from destination) to determine the (new) 'collection_name' parameter in the destination pattern based on the last material column of the assay (or alternatively another column given via `--collection-column`). If this is not used the "(?<sample>?)" match group is assumed to equal the irods collection names (this mirrors previous behaviour).
- The `cubi-tk …
=> feat: Update ingest-fastq, allow to match samples against assay table to determine collections names (#198)

cubi_tk/irods_common.py, tests/test_irods_common.py
fixes #200 
Note: Uploads cannot be cancelled by KeyboardInterrupt (caused by multiprocessing in irods client)
=> feat: Common functions for interfacing with python-irodsclient

cubi_tk/sodar/ingest_fastq.py, tests/test_sodar_ingest_fastq.py
Note: in the future the `SnappyItransferCommandBase` class should be changed to directly use the iRODSCommon functions for uplods, however that will need more work, so I"m only doing the necessary changes here for now.
=> feat: Switching `cubi-tk sodar ingest-fastq` from icommands to irods_common

cubi_tk/sodar/__init__.py, cubi_tk/sodar/lz_validate.py, tests/test_sodar_lz.py
Augmentation of #206 
closes #205
=> feat: Add new command sodar landing-zone-validate

cubi_tk/snappy/__init__.py, cubi_tk/snappy/common.py, cubi_tk/snappy/itransfer_sv_calling.py, tests/test_snappy_itransfer_sv_calling.py
Adding a new command to transfer all outout from snappy's sv_calling or sv_calling_targeted steps.
Includes autodetection of which step was run and autodetection of all used sv callers from snappy config.
=> feat: Adding cubi-tk snappy itransfer_sv_calling

cubi_tk/snappy/varfish_upload.py, requirements/base.txt
Previous varfish-cli versions always allowed case resubmission, the new 0.6.2 version does not do this by default, so we need the extra option in cubi-tk.
(I'm not sure why git thinks these other commits are part of this, they are already merged into main as of #222 )
=> feat: allow varfish case resubmission

cubi_tk/snappy/varfish_upload.py
Fix needed for #224 , the empty sting given to subprocess causes problems - using proper cmd line flag instead.
=> fix: varfish-upload subprocess submission

cubi_tk/irods/check.py, cubi_tk/irods_common.py, cubi_tk/snappy/check_remote.py, cubi_tk/snappy/pull_data_common.py, cubi_tk/snappy/pull_processed_data.py, cubi_tk/snappy/pull_raw_data.py, cubi_tk/sodar/__init__.py, cubi_tk/sodar/check_remote.py, cubi_tk/sodar/pull_data_collection.py, cubi_tk/sodar_common.py, tests/test_irods_common.py, tests/test_sodar_pull_data_collection.py
Fixes #226 
Replaces #208 
Partially fixes #201
=> feat: irods download refactoring and new generic sodar downloader with preset for dragen data (#226 )

src/cubi_tk/sodar/lz_list.py
=> feat: add `--filter-status` option for controlling which landing zones are listed

environment.yaml, uv.lock
Updates dependency versions in uv.lock. Also update minimum uv version in environment.yaml (cf. https://github.com/astral-sh/uv/issues/7533  [dynamic version in pyproject.toml vs version in uv.lock])
=> chore: Update uv lock

src/cubi_tk/sodar_common.py
added multi study support to assay search in sodar_common.py
=> fix: [#256] support for multiple studies and multiple assays in sodar_common.py

src/cubi_tk/irods_common.py
added last_env.json to check what the last authenticated sodar/irods instance was
=> fix: switch sodar profile with different irods_env
